<?xml version="1.0" encoding="utf-8"?><Database Name="portfolio" Class="dataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\portfolio.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="portfolioConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Scores" Member="Scores">
    <Type Name="Score">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="qid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="correct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Score" Member="User" ThisKey="uid" OtherKey="id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Question_Score" Member="Question" ThisKey="qid" OtherKey="id" Type="Question" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pswHash" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pswSalt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Score" Member="Scores" ThisKey="id" OtherKey="uid" Type="Score" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="question" Member="question1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="answer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="wrong1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="wrong2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="wrong3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Question_Score" Member="Scores" ThisKey="id" OtherKey="qid" Type="Score" />
    </Type>
  </Table>
</Database>